<?php

// Load .inc files
module_load_include('inc', 'gemini_migrate_d5', 'node');

function gemini_migrate_d5_menu() {
  $items = array();

  $items['admin/content/gemini_migrate_d5'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Drupal 5 to Drupal 7 Migration',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_nodes'),
    'access arguments' => array('administer site configuration'),
    'tab_root' => 'admin/content',
    'tab_parent' => 'admin/content'
  );

  $items['admin/content/gemini_migrate_d5/nodes'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Nodes',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/gemini_migrate_d5/users'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Users',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_users'),
    'access arguments' => array('administer site configuration'),
  );

  return $items; 
}

function gemini_migrate_d5_nodes() {
  return "<h3>Nodes</h3>";
}

function gemini_migrate_d5_form_nodes() {
  // drupal_set_message('Are you sure you want to run the custom import script?  No going back without re-installing the database!!!', 'warning');

  $form['node'] = array(
    '#type' => 'fieldset',
    '#title' => t('Node'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE
  );

  $header = array(
    'node_type' => t('Content Type'),
    'source_total' => t('Source'),
    'destination_total' => t('Destination'),
    'rollback' => t('Rollback')
  );

  $options = gemini_migrate_d5_get_node_type_table();

  $form['node']['table'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No users found'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  $form['submit_import'] = array(
    '#type' => 'submit',
    '#value' => t('Start import'),
  );

  // $result = gemini_migrate_d5_insert_field_data_body(1699);

  // $r = $result[0];
  // print_r($r->entity_id);
  return $form;
}

function gemini_migrate_d5_import_form_submit($form , $form_state) {
  $results = array_filter($form_state['values']['table']);
  // drupal_set_message(print_r($results , 1));

  // Insert selected content type nodes
  $result = gemini_migrate_d5_insert_nodes($results);

}