<?php

/*
 * This file only being used as a router
 */

// Load .inc files
module_load_include('inc', 'gemini_migrate_d5', 'node');
module_load_include('inc', 'gemini_migrate_d5', 'node_form');
module_load_include('inc', 'gemini_migrate_d5', 'user');
module_load_include('inc', 'gemini_migrate_d5', 'user_form');
module_load_include('inc', 'gemini_migrate_d5', 'menu');
module_load_include('inc', 'gemini_migrate_d5', 'menu_form');
module_load_include('inc', 'gemini_migrate_d5', 'url_alias');
module_load_include('inc', 'gemini_migrate_d5', 'url_alias_form');
module_load_include('inc', 'gemini_migrate_d5', 'file');
module_load_include('inc', 'gemini_migrate_d5', 'file_form');

function gemini_migrate_d5_menu() {
  $items = array();

  $items['admin/content/gemini_migrate_d5'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Drupal 5 to Drupal 7 Migration',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_node'),
    'access arguments' => array('administer site configuration'),
    'tab_root' => 'admin/content',
    'tab_parent' => 'admin/content'
  );

  $items['admin/content/gemini_migrate_d5/nodes'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Node',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/gemini_migrate_d5/users'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'User',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_user'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/gemini_migrate_d5/menu'] = array(
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'title' => 'Menu',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_menu'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/gemini_migrate_d5/url_alias'] = array(
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    'title' => 'URL Alias',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_url_alias'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/content/gemini_migrate_d5/file'] = array(
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
    'title' => 'File',
    'description' => 'Migrate content from Drupal 5 site to Drupal 7.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gemini_migrate_d5_form_file'),
    'access arguments' => array('administer site configuration'),
  );

  return $items; 
}